import { Parcel } from '@/type/parcel';

export const INITIAL_PARCELS: Record<string, Parcel> = {
  'PX-2026-001': {
    id: 'p1',
    waybillNumber: 'PX-2026-001',
    qrCodeData: 'PX-2026-001',
    senderName: 'John Maina',
    senderPhone: '0712345678',
    recipientName: 'Peter Kariuki',
    recipientPhone: '0722987654',
    recipientIdNumber: '32145678',
    originStage: 'Nairobi CBD',
    destinationStage: 'Eldoret',
    category: 'SMALL_BOX',
    description: 'Electronics & Spare Parts',
    declaredValueKsh: 15000,
    shippingFeeKsh: 500,
    status: 'IN_TRANSIT',
    assignedVehicleReg: 'KDA 123A',
    assignedTripId: 'TRIP-9901',
    createdAt: '2026-09-01 08:00 AM',
    events: [
      {
        id: 'e1',
        parcelId: 'p1',
        status: 'REGISTERED',
        locationName: 'Nairobi CBD Stage',
        timestamp: '08:00 AM',
        actorName: 'Clerk: Jane',
        actorRole: 'CLERK',
      },
      {
        id: 'e2',
        parcelId: 'p1',
        status: 'ASSIGNED_TO_TRIP',
        locationName: 'Nairobi CBD Stage',
        timestamp: '08:20 AM',
        actorName: 'System',
        actorRole: 'SYSTEM_GEOFENCE',
        vehicleReg: 'KDA 123A',
      },
      {
        id: 'e3',
        parcelId: 'p1',
        status: 'LOADED',
        locationName: 'Nairobi CBD Stage',
        timestamp: '08:35 AM',
        actorName: 'Conductor: Peter',
        actorRole: 'CONDUCTOR',
        vehicleReg: 'KDA 123A',
      },
      {
        id: 'e4',
        parcelId: 'p1',
        status: 'IN_TRANSIT',
        locationName: 'Naivasha Stage',
        timestamp: '09:45 AM',
        actorName: 'Conductor: Peter',
        actorRole: 'CONDUCTOR',
        vehicleReg: 'KDA 123A',
      },
    ],
  },
  'PX-2026-002': {
    id: 'p2',
    waybillNumber: 'PX-2026-002',
    qrCodeData: 'PX-2026-002',
    senderName: 'Mary Wanjiku',
    senderPhone: '0733112233',
    recipientName: 'Grace Akinyi',
    recipientPhone: '0755443322',
    recipientIdNumber: '44556677',
    originStage: 'Nairobi CBD',
    destinationStage: 'Nakuru',
    category: 'DOCUMENT',
    description: 'Legal Documents',
    declaredValueKsh: 2000,
    shippingFeeKsh: 300,
    status: 'REGISTERED',
    createdAt: '2026-09-01 10:15 AM',
    events: [
      {
        id: 'e10',
        parcelId: 'p2',
        status: 'REGISTERED',
        locationName: 'Nairobi CBD Stage',
        timestamp: '10:15 AM',
        actorName: 'Clerk: Jane',
        actorRole: 'CLERK',
      },
    ],
  },
};